<!-- pdf.blade.php -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Export statistics {{ date('Y_m_j') }}</title>
    <link rel="stylesheet" href=" {{ public_path() . '/css/report.css' }} ">
    <link rel="stylesheet" type="text/css" href=" {{ storage_path() . '/fonts/fontawesome/svgs/brands' }} ">
    <link rel="stylesheet" type="text/css" href=" {{ storage_path() . '/fonts/fontawesome/svgs/solid' }} ">
    <link rel="stylesheet" type="text/css" href=" {{ storage_path() . '/fonts/fontawesome/svgs/regular' }} ">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <style type="text/css">
      body {
        font-family: sans-serif;
        margin: 0;
        padding: 0;
      }
      table {
        width: 100%;
      }
      th {
        text-align: justify;
      }
      tr.first-tr {
        height: 50px;
      }
      td.additional_cost {
        background-color: #ff8a65;
        padding: 7px;
        text-align: center;
        color: white;
        border-radius: 5px;
      }
      div#title {
        height: 350px;
        background-image: url(http://localhost:4200/login-bg2.jpg);
        background-repeat: no-repeat;
        background-attachment: local; 
        background-position: 0% 80%;
        background-size: 100% auto;
      }
      div#bordered-title {
        border: #0097a7 5px solid;
        height: 20%;
        color: #0097a7;
        padding: 50px;
        margin: 50px auto 0 auto;
      }
      div#bordered-title p {
        font-size: 2em;
        margin: 20px;
      }
      div.card {
        box-shadow: 2px -1px 21px -5px lightgrey;
        min-width: 200px;
        border-top-right-radius: 15px;
        border-top-left-radius: 15px;
      }
      div.card-header {
        padding: 2% 12%;
        border-bottom-right-radius: 15px;
        border-bottom-left-radius: 15px;
        background-color: #0097a7;
        color: white;
        text-transform: uppercase;
        text-align: center; 
      }
      div.card-body {
        padding: 2% 12%;
        height: 150px;
        text-align: center;
        font-weight: bold;
        font-size: 3.5em;
      }
      div.project-info {
        color: #0097a7;
        text-align: center;
        padding-top: 20px;
      }
      section#numbers {
        padding-top: 50px;
        padding-bottom: 50px;
      }
      section#resources {
        background-color: #0097a7;
        padding: 20% 5% 10% 5%;
        color: white;
      }
      section#tasks {
        padding: 12% 5% 10% 5%;
      }
      div.resources-content {
        width: 350px;
      }
      p.resource-title {
        font-size: 2em;
        background-color: #00bcd4;
        padding: 17px;
        margin-top: 0;
        box-shadow: -4px 1px 16px -15px #006064;
      }
      span.ratio {
        margin-right: 45px;
        color: #00bcd4;
        font-weight: bold;
      }
      .illustrate {
        font-size: 19em;
      }
      .flex {
        display: flex;
        flex-wrap: nowrap;
        justify-content: space-between; 
      }
      .flex-around {
        display: flex;
        flex-wrap: nowrap;
        justify-content: space-around;
      }
      .dicret {
        font-size: 0.7em;
        color: white;
        position: absolute;
        top: 332px;
        left: 8px;
      }
      .no-style {
        text-decoration: none;
        list-style: none;
      }
    </style>
  </head>
  <body>
    <div id="title" class="flex">
      <div id="bordered-title">
        <p>{{ storage_path() }}</p>
      </div>
      <p><span class="dicret">Generated by HouraGANTT Team</span></p>
    </div>

    <section id="project">
      <div class="project-info">
        <ul class="no-style">
          <li>This has last for {{ $project->duration_days }} days</li>
          <li>You've created it the {{ $project->created_at }} </li>
          @if($project->description)
          <li>Description : {{ $project->description }} </li>
          @endif
        </ul>
      </div>
    </section>

    <section id="numbers">
      <div class="flex-around">
        <div class="card">
          <div class="card-body">
            <p> {{ $project->total_cost }} </p>
          </div>
          <div class="card-header">
            <p>EUR</p>
          </div>
        </div>

        <div class="card">
          <div class="card-body">
            <p>7</p>
          </div>
          <div class="card-header">
            <p>people</p>
          </div>
        </div>

        <div class="card">
          <div class="card-body">
            <p>109</p>
          </div>
          <div class="card-header">
            <p>tasks</p>
          </div>
        </div>
      </div>
    </section>

    <section id="resources">
      <div class="flex-around">
        <div class="illustrate">
          <i class="fab fa-angellist"></i>
        </div>
        <div class="resources-content">
          <p class="resource-title">Resources</p>
          <ul class="no-style">
            <li><span class="ratio">ratio</span>name</li>
            <li><span class="ratio">1,2  </span> fishguard 1</li>
            <li><span class="ratio">0,9  </span> Herlang okedo's </li>
            <li><span class="ratio">1,5  </span> dfc ooooooo</li>
            <li><span class="ratio">3,1  </span> Resource num 125545</li>
            <li><span class="ratio">2,4  </span> Someone else</li>
            <li><span class="ratio">0,8  </span> Master Ms SIMONE</li>
          </ul>
        </div>
      </div>
    </section>

    <section id="tasks">
      <table>
        <tr class="first-tr">
          <th></th>
          <th>From to</th>
          <th>Name</th>
          <th><i class="fas fa-euro-sign"></i></th>
        </tr>
        <tr>
          <td><i class="far fa-calendar-alt"></i></td>
          <td>09/10/19 <i class="fas fa-arrow-right"></i> 21/12/19</td>
          <td>This is another task</td>
          <td class="additional_cost">752</td>
        </tr>
        <tr>
          <td><i class="far fa-calendar-alt"></i></td>
          <td>29/03/19 <i class="fas fa-arrow-right"></i> 14/05/19</td>
          <td>Name of my Task 1</td>
          <td class="additional_cost">752</td>
        </tr>
        <tr>
          <td><i class="far fa-calendar-alt"></i></td>
          <td>29/03/19 <i class="fas fa-arrow-right"></i> 14/05/19</td>
          <td>Name of my Task 1</td>
          <td class="additional_cost">752</td>
        </tr>
      </table>
    </section>
  </body>
</html>